# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    packages:
      - libudunits2-dev # this is from https://stackoverflow.com/questions/54678006/rstudio-and-travis-ci-build-check-do-not-match-libudunits2-so
      - libgdal-dev # for the missing gdal.config and subseq sf install problem
